/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	subresourcev1alpha1 "github.com/kubrid/apiserver/pkg/apis/subresource/v1alpha1"
	clientset "github.com/kubrid/apiserver/pkg/client/clientset_generated/clientset"
	internalinterfaces "github.com/kubrid/apiserver/pkg/client/informers_generated/externalversions/internalinterfaces"
	v1alpha1 "github.com/kubrid/apiserver/pkg/client/listers_generated/subresource/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VirtualMachineInstanceInformer provides access to a shared informer and lister for
// VirtualMachineInstances.
type VirtualMachineInstanceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.VirtualMachineInstanceLister
}

type virtualMachineInstanceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewVirtualMachineInstanceInformer constructs a new informer for VirtualMachineInstance type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVirtualMachineInstanceInformer(client clientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVirtualMachineInstanceInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredVirtualMachineInstanceInformer constructs a new informer for VirtualMachineInstance type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVirtualMachineInstanceInformer(client clientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SubresourceV1alpha1().VirtualMachineInstances().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SubresourceV1alpha1().VirtualMachineInstances().Watch(context.TODO(), options)
			},
		},
		&subresourcev1alpha1.VirtualMachineInstance{},
		resyncPeriod,
		indexers,
	)
}

func (f *virtualMachineInstanceInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVirtualMachineInstanceInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *virtualMachineInstanceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&subresourcev1alpha1.VirtualMachineInstance{}, f.defaultInformer)
}

func (f *virtualMachineInstanceInformer) Lister() v1alpha1.VirtualMachineInstanceLister {
	return v1alpha1.NewVirtualMachineInstanceLister(f.Informer().GetIndexer())
}
