/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kubrid/apiserver/pkg/apis/subresource/v1alpha1"
	scheme "github.com/kubrid/apiserver/pkg/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VirtualMachineInstancePoweractionsGetter has a method to return a VirtualMachineInstancePoweractionInterface.
// A group's client should implement this interface.
type VirtualMachineInstancePoweractionsGetter interface {
	VirtualMachineInstancePoweractions(namespace string) VirtualMachineInstancePoweractionInterface
}

// VirtualMachineInstancePoweractionInterface has methods to work with VirtualMachineInstancePoweraction resources.
type VirtualMachineInstancePoweractionInterface interface {
	Create(ctx context.Context, virtualMachineInstancePoweraction *v1alpha1.VirtualMachineInstancePoweraction, opts v1.CreateOptions) (*v1alpha1.VirtualMachineInstancePoweraction, error)
	Update(ctx context.Context, virtualMachineInstancePoweraction *v1alpha1.VirtualMachineInstancePoweraction, opts v1.UpdateOptions) (*v1alpha1.VirtualMachineInstancePoweraction, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.VirtualMachineInstancePoweraction, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.VirtualMachineInstancePoweractionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VirtualMachineInstancePoweraction, err error)
	VirtualMachineInstancePoweractionExpansion
}

// virtualMachineInstancePoweractions implements VirtualMachineInstancePoweractionInterface
type virtualMachineInstancePoweractions struct {
	client rest.Interface
	ns     string
}

// newVirtualMachineInstancePoweractions returns a VirtualMachineInstancePoweractions
func newVirtualMachineInstancePoweractions(c *SubresourceV1alpha1Client, namespace string) *virtualMachineInstancePoweractions {
	return &virtualMachineInstancePoweractions{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the virtualMachineInstancePoweraction, and returns the corresponding virtualMachineInstancePoweraction object, and an error if there is any.
func (c *virtualMachineInstancePoweractions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VirtualMachineInstancePoweraction, err error) {
	result = &v1alpha1.VirtualMachineInstancePoweraction{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("virtualmachineinstancepoweractions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VirtualMachineInstancePoweractions that match those selectors.
func (c *virtualMachineInstancePoweractions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VirtualMachineInstancePoweractionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.VirtualMachineInstancePoweractionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("virtualmachineinstancepoweractions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested virtualMachineInstancePoweractions.
func (c *virtualMachineInstancePoweractions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("virtualmachineinstancepoweractions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a virtualMachineInstancePoweraction and creates it.  Returns the server's representation of the virtualMachineInstancePoweraction, and an error, if there is any.
func (c *virtualMachineInstancePoweractions) Create(ctx context.Context, virtualMachineInstancePoweraction *v1alpha1.VirtualMachineInstancePoweraction, opts v1.CreateOptions) (result *v1alpha1.VirtualMachineInstancePoweraction, err error) {
	result = &v1alpha1.VirtualMachineInstancePoweraction{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("virtualmachineinstancepoweractions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(virtualMachineInstancePoweraction).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a virtualMachineInstancePoweraction and updates it. Returns the server's representation of the virtualMachineInstancePoweraction, and an error, if there is any.
func (c *virtualMachineInstancePoweractions) Update(ctx context.Context, virtualMachineInstancePoweraction *v1alpha1.VirtualMachineInstancePoweraction, opts v1.UpdateOptions) (result *v1alpha1.VirtualMachineInstancePoweraction, err error) {
	result = &v1alpha1.VirtualMachineInstancePoweraction{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("virtualmachineinstancepoweractions").
		Name(virtualMachineInstancePoweraction.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(virtualMachineInstancePoweraction).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the virtualMachineInstancePoweraction and deletes it. Returns an error if one occurs.
func (c *virtualMachineInstancePoweractions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("virtualmachineinstancepoweractions").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *virtualMachineInstancePoweractions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("virtualmachineinstancepoweractions").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched virtualMachineInstancePoweraction.
func (c *virtualMachineInstancePoweractions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VirtualMachineInstancePoweraction, err error) {
	result = &v1alpha1.VirtualMachineInstancePoweraction{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("virtualmachineinstancepoweractions").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
