/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubrid/apiserver/pkg/apis/subresource/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVirtualMachineInstancePoweractions implements VirtualMachineInstancePoweractionInterface
type FakeVirtualMachineInstancePoweractions struct {
	Fake *FakeSubresourceV1alpha1
	ns   string
}

var virtualmachineinstancepoweractionsResource = schema.GroupVersionResource{Group: "subresource.core.kubrid.io", Version: "v1alpha1", Resource: "virtualmachineinstancepoweractions"}

var virtualmachineinstancepoweractionsKind = schema.GroupVersionKind{Group: "subresource.core.kubrid.io", Version: "v1alpha1", Kind: "VirtualMachineInstancePoweraction"}

// Get takes name of the virtualMachineInstancePoweraction, and returns the corresponding virtualMachineInstancePoweraction object, and an error if there is any.
func (c *FakeVirtualMachineInstancePoweractions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VirtualMachineInstancePoweraction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(virtualmachineinstancepoweractionsResource, c.ns, name), &v1alpha1.VirtualMachineInstancePoweraction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualMachineInstancePoweraction), err
}

// List takes label and field selectors, and returns the list of VirtualMachineInstancePoweractions that match those selectors.
func (c *FakeVirtualMachineInstancePoweractions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VirtualMachineInstancePoweractionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(virtualmachineinstancepoweractionsResource, virtualmachineinstancepoweractionsKind, c.ns, opts), &v1alpha1.VirtualMachineInstancePoweractionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VirtualMachineInstancePoweractionList{ListMeta: obj.(*v1alpha1.VirtualMachineInstancePoweractionList).ListMeta}
	for _, item := range obj.(*v1alpha1.VirtualMachineInstancePoweractionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested virtualMachineInstancePoweractions.
func (c *FakeVirtualMachineInstancePoweractions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(virtualmachineinstancepoweractionsResource, c.ns, opts))

}

// Create takes the representation of a virtualMachineInstancePoweraction and creates it.  Returns the server's representation of the virtualMachineInstancePoweraction, and an error, if there is any.
func (c *FakeVirtualMachineInstancePoweractions) Create(ctx context.Context, virtualMachineInstancePoweraction *v1alpha1.VirtualMachineInstancePoweraction, opts v1.CreateOptions) (result *v1alpha1.VirtualMachineInstancePoweraction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(virtualmachineinstancepoweractionsResource, c.ns, virtualMachineInstancePoweraction), &v1alpha1.VirtualMachineInstancePoweraction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualMachineInstancePoweraction), err
}

// Update takes the representation of a virtualMachineInstancePoweraction and updates it. Returns the server's representation of the virtualMachineInstancePoweraction, and an error, if there is any.
func (c *FakeVirtualMachineInstancePoweractions) Update(ctx context.Context, virtualMachineInstancePoweraction *v1alpha1.VirtualMachineInstancePoweraction, opts v1.UpdateOptions) (result *v1alpha1.VirtualMachineInstancePoweraction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(virtualmachineinstancepoweractionsResource, c.ns, virtualMachineInstancePoweraction), &v1alpha1.VirtualMachineInstancePoweraction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualMachineInstancePoweraction), err
}

// Delete takes name of the virtualMachineInstancePoweraction and deletes it. Returns an error if one occurs.
func (c *FakeVirtualMachineInstancePoweractions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(virtualmachineinstancepoweractionsResource, c.ns, name), &v1alpha1.VirtualMachineInstancePoweraction{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVirtualMachineInstancePoweractions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(virtualmachineinstancepoweractionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VirtualMachineInstancePoweractionList{})
	return err
}

// Patch applies the patch and returns the patched virtualMachineInstancePoweraction.
func (c *FakeVirtualMachineInstancePoweractions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VirtualMachineInstancePoweraction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(virtualmachineinstancepoweractionsResource, c.ns, name, pt, data, subresources...), &v1alpha1.VirtualMachineInstancePoweraction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualMachineInstancePoweraction), err
}
