/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by apiregister-gen. DO NOT EDIT.

package subresource

import (
	"context"
	"fmt"

	"k8s.io/apimachinery/pkg/apis/meta/internalversion"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apiserver/pkg/registry/rest"
	"sigs.k8s.io/apiserver-builder-alpha/pkg/builders"
)

var (
	SubresourceVirtualMachineInstanceStorage = builders.NewApiResource( // Resource status endpoint
		InternalVirtualMachineInstance,
		func() runtime.Object { return &VirtualMachineInstance{} },     // Register versioned resource
		func() runtime.Object { return &VirtualMachineInstanceList{} }, // Register versioned resource list
		&VirtualMachineInstanceStrategy{builders.StorageStrategySingleton},
	)
	InternalVirtualMachineInstance = builders.NewInternalResource(
		"virtualmachineinstances",
		"VirtualMachineInstance",
		func() runtime.Object { return &VirtualMachineInstance{} },
		func() runtime.Object { return &VirtualMachineInstanceList{} },
	)
	InternalVirtualMachineInstanceStatus = builders.NewInternalResourceStatus(
		"virtualmachineinstances",
		"VirtualMachineInstanceStatus",
		func() runtime.Object { return &VirtualMachineInstance{} },
		func() runtime.Object { return &VirtualMachineInstanceList{} },
	)
	InternalVirtualMachineInstancePoweractionREST = builders.NewInternalSubresource(
		"virtualmachineinstances", "VirtualMachineInstancePoweraction", "poweraction",
		func() runtime.Object { return &VirtualMachineInstancePoweraction{} },
	)
	// Registered resources and subresources
	ApiVersion = builders.NewApiGroup("subresource.core.kubrid.io").WithKinds(
		InternalVirtualMachineInstance,
		InternalVirtualMachineInstanceStatus,
		InternalVirtualMachineInstancePoweractionREST,
	)

	// Required by code generated by go2idl
	AddToScheme = (&runtime.SchemeBuilder{
		ApiVersion.SchemeBuilder.AddToScheme,
		RegisterDefaults,
	}).AddToScheme
	SchemeBuilder      = ApiVersion.SchemeBuilder
	localSchemeBuilder = &SchemeBuilder
	SchemeGroupVersion = ApiVersion.GroupVersion
)

// Required by code generated by go2idl
// Kind takes an unqualified kind and returns a Group qualified GroupKind
func Kind(kind string) schema.GroupKind {
	return SchemeGroupVersion.WithKind(kind).GroupKind()
}

// Required by code generated by go2idl
// Resource takes an unqualified resource and returns a Group qualified GroupResource
func Resource(resource string) schema.GroupResource {
	return SchemeGroupVersion.WithResource(resource).GroupResource()
}

// +genclient
// +genclient:nonNamespaced
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type VirtualMachineInstance struct {
	metav1.TypeMeta
	metav1.ObjectMeta
	Spec   VirtualMachineInstanceSpec
	Status VirtualMachineInstanceStatus
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type VirtualMachineInstancePoweraction struct {
	metav1.TypeMeta
	metav1.ObjectMeta
}

type VirtualMachineInstanceSpec struct {
}

type VirtualMachineInstanceStatus struct {
}

//
// VirtualMachineInstance Functions and Structs
//
// +k8s:deepcopy-gen=false
type VirtualMachineInstanceStrategy struct {
	builders.DefaultStorageStrategy
}

// +k8s:deepcopy-gen=false
type VirtualMachineInstanceStatusStrategy struct {
	builders.DefaultStatusStorageStrategy
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type VirtualMachineInstanceList struct {
	metav1.TypeMeta
	metav1.ListMeta
	Items []VirtualMachineInstance
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type VirtualMachineInstancePoweractionList struct {
	metav1.TypeMeta
	metav1.ListMeta
	Items []VirtualMachineInstancePoweraction
}

func (VirtualMachineInstance) NewStatus() interface{} {
	return VirtualMachineInstanceStatus{}
}

func (pc *VirtualMachineInstance) GetStatus() interface{} {
	return pc.Status
}

func (pc *VirtualMachineInstance) SetStatus(s interface{}) {
	pc.Status = s.(VirtualMachineInstanceStatus)
}

func (pc *VirtualMachineInstance) GetSpec() interface{} {
	return pc.Spec
}

func (pc *VirtualMachineInstance) SetSpec(s interface{}) {
	pc.Spec = s.(VirtualMachineInstanceSpec)
}

func (pc *VirtualMachineInstance) GetObjectMeta() *metav1.ObjectMeta {
	return &pc.ObjectMeta
}

func (pc *VirtualMachineInstance) SetGeneration(generation int64) {
	pc.ObjectMeta.Generation = generation
}

func (pc VirtualMachineInstance) GetGeneration() int64 {
	return pc.ObjectMeta.Generation
}

// Registry is an interface for things that know how to store VirtualMachineInstance.
// +k8s:deepcopy-gen=false
type VirtualMachineInstanceRegistry interface {
	ListVirtualMachineInstances(ctx context.Context, options *internalversion.ListOptions) (*VirtualMachineInstanceList, error)
	GetVirtualMachineInstance(ctx context.Context, id string, options *metav1.GetOptions) (*VirtualMachineInstance, error)
	CreateVirtualMachineInstance(ctx context.Context, id *VirtualMachineInstance) (*VirtualMachineInstance, error)
	UpdateVirtualMachineInstance(ctx context.Context, id *VirtualMachineInstance) (*VirtualMachineInstance, error)
	DeleteVirtualMachineInstance(ctx context.Context, id string) (bool, error)
}

// NewRegistry returns a new Registry interface for the given Storage. Any mismatched types will panic.
func NewVirtualMachineInstanceRegistry(sp builders.StandardStorageProvider) VirtualMachineInstanceRegistry {
	return &storageVirtualMachineInstance{sp}
}

// Implement Registry
// storage puts strong typing around storage calls
// +k8s:deepcopy-gen=false
type storageVirtualMachineInstance struct {
	builders.StandardStorageProvider
}

func (s *storageVirtualMachineInstance) ListVirtualMachineInstances(ctx context.Context, options *internalversion.ListOptions) (*VirtualMachineInstanceList, error) {
	if options != nil && options.FieldSelector != nil && !options.FieldSelector.Empty() {
		return nil, fmt.Errorf("field selector not supported yet")
	}
	st := s.GetStandardStorage()
	obj, err := st.List(ctx, options)
	if err != nil {
		return nil, err
	}
	return obj.(*VirtualMachineInstanceList), err
}

func (s *storageVirtualMachineInstance) GetVirtualMachineInstance(ctx context.Context, id string, options *metav1.GetOptions) (*VirtualMachineInstance, error) {
	st := s.GetStandardStorage()
	obj, err := st.Get(ctx, id, options)
	if err != nil {
		return nil, err
	}
	return obj.(*VirtualMachineInstance), nil
}

func (s *storageVirtualMachineInstance) CreateVirtualMachineInstance(ctx context.Context, object *VirtualMachineInstance) (*VirtualMachineInstance, error) {
	st := s.GetStandardStorage()
	obj, err := st.Create(ctx, object, nil, &metav1.CreateOptions{})
	if err != nil {
		return nil, err
	}
	return obj.(*VirtualMachineInstance), nil
}

func (s *storageVirtualMachineInstance) UpdateVirtualMachineInstance(ctx context.Context, object *VirtualMachineInstance) (*VirtualMachineInstance, error) {
	st := s.GetStandardStorage()
	obj, _, err := st.Update(ctx, object.Name, rest.DefaultUpdatedObjectInfo(object), nil, nil, false, &metav1.UpdateOptions{})
	if err != nil {
		return nil, err
	}
	return obj.(*VirtualMachineInstance), nil
}

func (s *storageVirtualMachineInstance) DeleteVirtualMachineInstance(ctx context.Context, id string) (bool, error) {
	st := s.GetStandardStorage()
	_, sync, err := st.Delete(ctx, id, nil, &metav1.DeleteOptions{})
	return sync, err
}
