// +build !ignore_autogenerated

/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	subresource "github.com/kubrid/apiserver/pkg/apis/subresource"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*VirtualMachineInstance)(nil), (*subresource.VirtualMachineInstance)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineInstance_To_subresource_VirtualMachineInstance(a.(*VirtualMachineInstance), b.(*subresource.VirtualMachineInstance), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*subresource.VirtualMachineInstance)(nil), (*VirtualMachineInstance)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_subresource_VirtualMachineInstance_To_v1alpha1_VirtualMachineInstance(a.(*subresource.VirtualMachineInstance), b.(*VirtualMachineInstance), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineInstanceList)(nil), (*subresource.VirtualMachineInstanceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineInstanceList_To_subresource_VirtualMachineInstanceList(a.(*VirtualMachineInstanceList), b.(*subresource.VirtualMachineInstanceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*subresource.VirtualMachineInstanceList)(nil), (*VirtualMachineInstanceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_subresource_VirtualMachineInstanceList_To_v1alpha1_VirtualMachineInstanceList(a.(*subresource.VirtualMachineInstanceList), b.(*VirtualMachineInstanceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineInstancePoweraction)(nil), (*subresource.VirtualMachineInstancePoweraction)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineInstancePoweraction_To_subresource_VirtualMachineInstancePoweraction(a.(*VirtualMachineInstancePoweraction), b.(*subresource.VirtualMachineInstancePoweraction), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*subresource.VirtualMachineInstancePoweraction)(nil), (*VirtualMachineInstancePoweraction)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_subresource_VirtualMachineInstancePoweraction_To_v1alpha1_VirtualMachineInstancePoweraction(a.(*subresource.VirtualMachineInstancePoweraction), b.(*VirtualMachineInstancePoweraction), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineInstancePoweractionList)(nil), (*subresource.VirtualMachineInstancePoweractionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineInstancePoweractionList_To_subresource_VirtualMachineInstancePoweractionList(a.(*VirtualMachineInstancePoweractionList), b.(*subresource.VirtualMachineInstancePoweractionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*subresource.VirtualMachineInstancePoweractionList)(nil), (*VirtualMachineInstancePoweractionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_subresource_VirtualMachineInstancePoweractionList_To_v1alpha1_VirtualMachineInstancePoweractionList(a.(*subresource.VirtualMachineInstancePoweractionList), b.(*VirtualMachineInstancePoweractionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineInstanceSpec)(nil), (*subresource.VirtualMachineInstanceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineInstanceSpec_To_subresource_VirtualMachineInstanceSpec(a.(*VirtualMachineInstanceSpec), b.(*subresource.VirtualMachineInstanceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*subresource.VirtualMachineInstanceSpec)(nil), (*VirtualMachineInstanceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_subresource_VirtualMachineInstanceSpec_To_v1alpha1_VirtualMachineInstanceSpec(a.(*subresource.VirtualMachineInstanceSpec), b.(*VirtualMachineInstanceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineInstanceStatus)(nil), (*subresource.VirtualMachineInstanceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineInstanceStatus_To_subresource_VirtualMachineInstanceStatus(a.(*VirtualMachineInstanceStatus), b.(*subresource.VirtualMachineInstanceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*subresource.VirtualMachineInstanceStatus)(nil), (*VirtualMachineInstanceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_subresource_VirtualMachineInstanceStatus_To_v1alpha1_VirtualMachineInstanceStatus(a.(*subresource.VirtualMachineInstanceStatus), b.(*VirtualMachineInstanceStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_VirtualMachineInstance_To_subresource_VirtualMachineInstance(in *VirtualMachineInstance, out *subresource.VirtualMachineInstance, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_VirtualMachineInstanceSpec_To_subresource_VirtualMachineInstanceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_VirtualMachineInstanceStatus_To_subresource_VirtualMachineInstanceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_VirtualMachineInstance_To_subresource_VirtualMachineInstance is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineInstance_To_subresource_VirtualMachineInstance(in *VirtualMachineInstance, out *subresource.VirtualMachineInstance, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineInstance_To_subresource_VirtualMachineInstance(in, out, s)
}

func autoConvert_subresource_VirtualMachineInstance_To_v1alpha1_VirtualMachineInstance(in *subresource.VirtualMachineInstance, out *VirtualMachineInstance, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_subresource_VirtualMachineInstanceSpec_To_v1alpha1_VirtualMachineInstanceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_subresource_VirtualMachineInstanceStatus_To_v1alpha1_VirtualMachineInstanceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_subresource_VirtualMachineInstance_To_v1alpha1_VirtualMachineInstance is an autogenerated conversion function.
func Convert_subresource_VirtualMachineInstance_To_v1alpha1_VirtualMachineInstance(in *subresource.VirtualMachineInstance, out *VirtualMachineInstance, s conversion.Scope) error {
	return autoConvert_subresource_VirtualMachineInstance_To_v1alpha1_VirtualMachineInstance(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachineInstanceList_To_subresource_VirtualMachineInstanceList(in *VirtualMachineInstanceList, out *subresource.VirtualMachineInstanceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]subresource.VirtualMachineInstance)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_VirtualMachineInstanceList_To_subresource_VirtualMachineInstanceList is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineInstanceList_To_subresource_VirtualMachineInstanceList(in *VirtualMachineInstanceList, out *subresource.VirtualMachineInstanceList, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineInstanceList_To_subresource_VirtualMachineInstanceList(in, out, s)
}

func autoConvert_subresource_VirtualMachineInstanceList_To_v1alpha1_VirtualMachineInstanceList(in *subresource.VirtualMachineInstanceList, out *VirtualMachineInstanceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]VirtualMachineInstance)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_subresource_VirtualMachineInstanceList_To_v1alpha1_VirtualMachineInstanceList is an autogenerated conversion function.
func Convert_subresource_VirtualMachineInstanceList_To_v1alpha1_VirtualMachineInstanceList(in *subresource.VirtualMachineInstanceList, out *VirtualMachineInstanceList, s conversion.Scope) error {
	return autoConvert_subresource_VirtualMachineInstanceList_To_v1alpha1_VirtualMachineInstanceList(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachineInstancePoweraction_To_subresource_VirtualMachineInstancePoweraction(in *VirtualMachineInstancePoweraction, out *subresource.VirtualMachineInstancePoweraction, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	return nil
}

// Convert_v1alpha1_VirtualMachineInstancePoweraction_To_subresource_VirtualMachineInstancePoweraction is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineInstancePoweraction_To_subresource_VirtualMachineInstancePoweraction(in *VirtualMachineInstancePoweraction, out *subresource.VirtualMachineInstancePoweraction, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineInstancePoweraction_To_subresource_VirtualMachineInstancePoweraction(in, out, s)
}

func autoConvert_subresource_VirtualMachineInstancePoweraction_To_v1alpha1_VirtualMachineInstancePoweraction(in *subresource.VirtualMachineInstancePoweraction, out *VirtualMachineInstancePoweraction, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	return nil
}

// Convert_subresource_VirtualMachineInstancePoweraction_To_v1alpha1_VirtualMachineInstancePoweraction is an autogenerated conversion function.
func Convert_subresource_VirtualMachineInstancePoweraction_To_v1alpha1_VirtualMachineInstancePoweraction(in *subresource.VirtualMachineInstancePoweraction, out *VirtualMachineInstancePoweraction, s conversion.Scope) error {
	return autoConvert_subresource_VirtualMachineInstancePoweraction_To_v1alpha1_VirtualMachineInstancePoweraction(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachineInstancePoweractionList_To_subresource_VirtualMachineInstancePoweractionList(in *VirtualMachineInstancePoweractionList, out *subresource.VirtualMachineInstancePoweractionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]subresource.VirtualMachineInstancePoweraction)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_VirtualMachineInstancePoweractionList_To_subresource_VirtualMachineInstancePoweractionList is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineInstancePoweractionList_To_subresource_VirtualMachineInstancePoweractionList(in *VirtualMachineInstancePoweractionList, out *subresource.VirtualMachineInstancePoweractionList, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineInstancePoweractionList_To_subresource_VirtualMachineInstancePoweractionList(in, out, s)
}

func autoConvert_subresource_VirtualMachineInstancePoweractionList_To_v1alpha1_VirtualMachineInstancePoweractionList(in *subresource.VirtualMachineInstancePoweractionList, out *VirtualMachineInstancePoweractionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]VirtualMachineInstancePoweraction)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_subresource_VirtualMachineInstancePoweractionList_To_v1alpha1_VirtualMachineInstancePoweractionList is an autogenerated conversion function.
func Convert_subresource_VirtualMachineInstancePoweractionList_To_v1alpha1_VirtualMachineInstancePoweractionList(in *subresource.VirtualMachineInstancePoweractionList, out *VirtualMachineInstancePoweractionList, s conversion.Scope) error {
	return autoConvert_subresource_VirtualMachineInstancePoweractionList_To_v1alpha1_VirtualMachineInstancePoweractionList(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachineInstanceSpec_To_subresource_VirtualMachineInstanceSpec(in *VirtualMachineInstanceSpec, out *subresource.VirtualMachineInstanceSpec, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_VirtualMachineInstanceSpec_To_subresource_VirtualMachineInstanceSpec is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineInstanceSpec_To_subresource_VirtualMachineInstanceSpec(in *VirtualMachineInstanceSpec, out *subresource.VirtualMachineInstanceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineInstanceSpec_To_subresource_VirtualMachineInstanceSpec(in, out, s)
}

func autoConvert_subresource_VirtualMachineInstanceSpec_To_v1alpha1_VirtualMachineInstanceSpec(in *subresource.VirtualMachineInstanceSpec, out *VirtualMachineInstanceSpec, s conversion.Scope) error {
	return nil
}

// Convert_subresource_VirtualMachineInstanceSpec_To_v1alpha1_VirtualMachineInstanceSpec is an autogenerated conversion function.
func Convert_subresource_VirtualMachineInstanceSpec_To_v1alpha1_VirtualMachineInstanceSpec(in *subresource.VirtualMachineInstanceSpec, out *VirtualMachineInstanceSpec, s conversion.Scope) error {
	return autoConvert_subresource_VirtualMachineInstanceSpec_To_v1alpha1_VirtualMachineInstanceSpec(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachineInstanceStatus_To_subresource_VirtualMachineInstanceStatus(in *VirtualMachineInstanceStatus, out *subresource.VirtualMachineInstanceStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_VirtualMachineInstanceStatus_To_subresource_VirtualMachineInstanceStatus is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineInstanceStatus_To_subresource_VirtualMachineInstanceStatus(in *VirtualMachineInstanceStatus, out *subresource.VirtualMachineInstanceStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineInstanceStatus_To_subresource_VirtualMachineInstanceStatus(in, out, s)
}

func autoConvert_subresource_VirtualMachineInstanceStatus_To_v1alpha1_VirtualMachineInstanceStatus(in *subresource.VirtualMachineInstanceStatus, out *VirtualMachineInstanceStatus, s conversion.Scope) error {
	return nil
}

// Convert_subresource_VirtualMachineInstanceStatus_To_v1alpha1_VirtualMachineInstanceStatus is an autogenerated conversion function.
func Convert_subresource_VirtualMachineInstanceStatus_To_v1alpha1_VirtualMachineInstanceStatus(in *subresource.VirtualMachineInstanceStatus, out *VirtualMachineInstanceStatus, s conversion.Scope) error {
	return autoConvert_subresource_VirtualMachineInstanceStatus_To_v1alpha1_VirtualMachineInstanceStatus(in, out, s)
}
